In [313]:
%load_ext autoreload
%autoreload 2

In [314]:
import sqlite3
import pandas as pd
from experiment import *

## Load Data

In [219]:
con = sqlite3.connect('../input/database.sqlite')

### Mobiles

![](./images/mobile.png)

#### Features

`drawbridge_handle`, **`device_id`**, `device_type`, `device_os`, `country`,

`anonymous_c0`, `anonymous_c1`, `anonymous_c2`, `anonymous_5`, `anonymous_6`, `anonymous_7`

In [220]:
query = 'select * from devices'
mobiles = pd.read_sql(query, con)
mobiles

,drawbridge_handle,device_id,device_type,device_os,country,anonymous_c0,anonymous_c1,anonymous_c2,anonymous_5,anonymous_6,anonymous_7
0,handle_292447,id_1000002,devtype_2,devos_138,country_146,1,anonymous_c1_331,anonymous_c2_23084,34,1,204
1,handle_1272807,id_1000061,devtype_2,devos_157,country_146,0,anonymous_c1_1350,anonymous_c2_3147,51,1,203
2,handle_1644226,id_1000068,devtype_2,devos_157,country_146,0,anonymous_c1_1166,anonymous_c2_11093,41,1,204
3,handle_1634852,id_1000149,devtype_4,devos_133,country_146,1,anonymous_c1_1260,anonymous_c2_2456,10,25,198
4,handle_1189159,id_1000202,devtype_4,devos_7,country_146,0,anonymous_c1_917,anonymous_c2_19317,5,1,204
5,handle_1403177,id_1000203,devtype_4,devos_68,country_146,-1,anonymous_c1_679,anonymous_c2_8088,75,1,204
6,handle_710800,id_1000235,devtype_2,devos_72,country_146,0,anonymous_c1_336,anonymous_c2_868,14,1,204
7,handle_1493525,id_1000243,devtype_2,devos_138,country_146,1,anonymous_c1_1179,anonymous_c2_9528,52,74,204
8,handle_312878,id_1000314,devtype_2,devos_138,country_146,1,anonymous_c1_1089,anonymous_c2_23390,3,1,154
9,handle_770055,id_1000317,devtype_4,devos_68,country_146,-1,anonymous_c1_339,anonymous_c2_10927,14,1,202
10,handle_1116987,id_100034,devtype_2,devos_157,country_146,1,anonymous_c1_1366,anonymous_c2_16512,52,1,204
11,handle_450234,id_10004,devtype_4,devos_114,country_146,1,anonymous_c1_204,anonymous_c2_7923,33,116,204
12,handle_704615,id_1000435,devtype_4,devos_68,country_146,0,anonymous_c1_673,anonymous_c2_7769,3,1,204
13,handle_769424,id_1000496,devtype_4,devos_67,country_146,0,anonymous_c1_814,anonymous_c2_17346,30,126,204
14,handle_216620,id_1000551,devtype_4,devos_119,country_146,-1,anonymous_c1_1307,anonymous_c2_2864,40,1,185
15,handle_1740733,id_1000566,devtype_2,devos_157,country_146,0,anonymous_c1_241,anonymous_c2_27125,52,1,204
16,handle_698393,id_100061,devtype_2,devos_72,country_146,0,anonymous_c1_1217,anonymous_c2_28721,5,1,204
17,handle_1426365,id_1000623,devtype_2,devos_72,country_146,1,anonymous_c1_255,anonymous_c2_2657,21,1,197
18,handle_718906,id_1000676,devtype_4,devos_68,country_146,1,anonymous_c1_914,-1,52,111,204
19,handle_58021,id_1000680,devtype_2,devos_128,country_146,1,anonymous_c1_1307,-1,5,1,204
20,handle_239825,id_1000736,devtype_2,devos_157,country_146,0,anonymous_c1_400,anonymous_c2_4241,6,1,201
21,handle_1066254,id_1000767,devtype_5,devos_139,country_146,-1,anonymous_c1_1311,anonymous_c2_3686,1,74,161
22,handle_424062,id_1000773,devtype_2,devos_72,country_146,1,anonymous_c1_165,anonymous_c2_231,23,1,198
23,handle_443284,id_1000808,devtype_4,devos_68,country_146,0,anonymous_c1_1351,anonymous_c2_8749,5,1,189
24,handle_750432,id_1000815,devtype_2,devos_157,-1,0,anonymous_c1_393,anonymous_c2_11841,30,143,204
25,handle_224802,id_1000858,devtype_2,devos_138,country_146,1,anonymous_c1_877,anonymous_c2_4578,22,67,179
26,handle_1665403,id_1000925,devtype_2,devos_72,country_146,0,anonymous_c1_1179,anonymous_c2_25396,14,39,200
27,handle_1136583,id_1000957,devtype_4,devos_68,country_146,-1,anonymous_c1_814,anonymous_c2_15091,8,1,196
28,handle_1584897,id_1000972,devtype_2,devos_157,country_146,1,anonymous_c1_255,anonymous_c2_5556,33,1,204
29,handle_496279,id_1000991,devtype_2,devos_157,country_146,0,anonymous_c1_71,anonymous_c2_2661,18,4,204
...,...,...,...,...,...,...,...,...,...,...,...
203896,-1,id_997605,devtype_4,devos_68,country_146,1,-1,-1,10,1,202
203897,-1,id_997854,devtype_4,devos_119,country_146,-1,-1,-1,21,100,191
203898,-1,id_997957,devtype_2,devos_36,country_146,0,-1,-1,2,1,194
203899,-1,id_997990,devtype_2,devos_138,country_146,0,anonymous_c1_884,-1,49,1,204
203900,-1,id_998035,devtype_4,devos_97,country_146,0,anonymous_c1_1015,anonymous_c2_31142,52,1,204
203901,-1,id_998069,devtype_4,devos_44,country_169,-1,anonymous_c1_559,anonymous_c2_23001,41,1,198
203902,-1,id_998130,devtype_2,devos_12,country_146,1,anonymous_c1_786,anonymous_c2_15976,50,60,203
203903,-1,id_998218,devtype_4,devos_133,country_146,0,anonymous_c1_1123,anonymous_c2_12270,14,1,204
203904,-1,id_998315,devtype_6,devos_157,country_146,0,anonymous_c1_1197,anonymous_c2_10383,11,1,202
203905,-1,id_998345,devtype_4,devos_68,country_146,1,-1,-1,3,1,195
203906,-1,id_998508,devtype_2,devos_157,country_169,1,anonymous_c1_543,anonymous_c2_1477,50,1,204
203907,-1,id_998566,devtype_2,devos_159,country_146,0,anonymous_c1_859,anonymous_c2_13418,13,94,202
203908,-1,id_998593,devtype_4,devos_68,country_146,1,anonymous_c1_1256,anonymous_c2_18846,11,106,193
203909,-1,id_998606,devtype_2,devos_157,country_146,0,-1,-1,30,25,203
203910,-1,id_998731,devtype_2,devos_36,country_146,0,anonymous_c1_204,anonymous_c2_30609,21,25,204
203911,-1,id_998794,devtype_4,devos_119,country_146,0,anonymous_c1_1187,anonymous_c2_3290,1,60,204
203912,-1,id_998942,devtype_2,devos_157,country_146,1,anonymous_c1_13,anonymous_c2_28686,27,81,204
203913,-1,id_998944,devtype_2,devos_157,country_201,-1,anonymous_c1_885,anonymous_c2_29080,52,1,204
203914,-1,id_999134,devtype_4,devos_68,country_146,-1,anonymous_c1_1086,anonymous_c2_13905,22,4,184
203915,-1,id_999179,devtype_4,devos_68,country_146,0,anonymous_c1_1164,anonymous_c2_24607,12,1,192
203916,-1,id_99918,devtype_4,devos_97,country_201,-1,anonymous_c1_1343,-1,1,1,177
203917,-1,id_999274,devtype_2,devos_159,country_146,-1,anonymous_c1_1307,-1,9,1,179
203918,-1,id_999338,devtype_4,devos_112,country_146,-1,anonymous_c1_1253,anonymous_c2_16263,4,1,204
203919,-1,id_999342,devtype_4,devos_133,country_146,-1,anonymous_c1_204,anonymous_c2_12471,10,1,201
203920,-1,id_999388,devtype_4,devos_119,country_146,0,anonymous_c1_1053,anonymous_c2_20037,20,1,196
203921,-1,id_999467,devtype_2,devos_138,country_146,1,anonymous_c1_492,anonymous_c2_24538,6,1,193
203922,-1,id_999511,devtype_2,devos_157,country_146,-1,-1,-1,39,1,204
203923,-1,id_999623,devtype_2,devos_159,country_146,0,-1,-1,16,67,189
203924,-1,id_999744,devtype_2,devos_138,country_146,0,anonymous_c1_255,-1,29,1,180
203925,-1,id_999865,devtype_5,devos_143,country_146,0,anonymous_c1_614,anonymous_c2_12852,8,1,194

### Desktops

![](./images/desktop.png)

#### Features

`drawbridge_handle`, **`cookie_id`**, `computer_os_type`, `browser_version`, `country`,

`anonymous_c0`, `anonymous_c1`, `anonymous_c2`, `anonymous_5`, `anonymous_6`, `anonymous_7`

In [263]:
query = 'select * from cookies'
desktops = pd.read_sql(query, con)
desktops

,drawbridge_handle,cookie_id,computer_os_type,browser_version,country,anonymous_c0,anonymous_c1,anonymous_c2,anonymous_5,anonymous_6,anonymous_7
0,-1,id_10,computer_os_type_203,computer_browser_version_1158,country_146,1,anonymous_c1_1307,anonymous_c2_18778,15,1,204
1,handle_609762,id_100,computer_os_type_133,computer_browser_version_875,country_146,1,anonymous_c1_753,-1,41,1,204
2,handle_1622320,id_1000,computer_os_type_203,computer_browser_version_36,country_146,0,anonymous_c1_906,anonymous_c2_751,40,140,204
3,-1,id_10000,computer_os_type_203,computer_browser_version_36,country_146,1,anonymous_c1_255,anonymous_c2_2725,34,140,204
4,handle_1286628,id_100000,computer_os_type_203,computer_browser_version_875,country_146,0,anonymous_c1_255,anonymous_c2_235,52,134,204
5,-1,id_1000003,computer_os_type_200,computer_browser_version_683,country_146,0,anonymous_c1_983,-1,23,67,204
6,handle_226230,id_1000006,computer_os_type_203,computer_browser_version_1238,-1,1,-1,-1,1,183,183
7,-1,id_1000007,computer_os_type_133,computer_browser_version_36,country_177,-1,anonymous_c1_431,anonymous_c2_22023,7,141,197
8,handle_15216,id_1000008,computer_os_type_200,computer_browser_version_482,country_146,0,anonymous_c1_1179,anonymous_c2_2683,40,74,204
9,handle_1043549,id_1000009,computer_os_type_133,computer_browser_version_1158,country_146,0,anonymous_c1_1307,anonymous_c2_6720,11,161,203
10,handle_1303003,id_100001,computer_os_type_133,computer_browser_version_683,country_146,0,anonymous_c1_493,anonymous_c2_27360,9,136,204
11,-1,id_1000014,computer_os_type_203,computer_browser_version_36,country_146,0,anonymous_c1_1250,anonymous_c2_19302,89,140,204
12,handle_1929259,id_1000015,computer_os_type_26,computer_browser_version_450,country_146,0,anonymous_c1_550,anonymous_c2_1338,46,60,204
13,handle_853638,id_1000017,computer_os_type_133,computer_browser_version_1238,country_146,1,anonymous_c1_639,anonymous_c2_27190,15,1,165
14,handle_1204416,id_1000022,computer_os_type_185,computer_browser_version_897,-1,0,-1,-1,7,144,153
15,handle_1500607,id_1000025,computer_os_type_203,computer_browser_version_875,country_146,0,anonymous_c1_317,anonymous_c2_3469,11,1,200
16,handle_874748,id_1000026,computer_os_type_203,computer_browser_version_36,country_146,0,anonymous_c1_673,anonymous_c2_17315,15,165,190
17,-1,id_1000028,computer_os_type_203,computer_browser_version_611,country_146,1,-1,-1,11,150,204
18,handle_1257881,id_1000033,computer_os_type_146,computer_browser_version_548,-1,0,anonymous_c1_1128,-1,13,1,204
19,handle_2002832,id_1000034,-1,computer_browser_version_1123,country_146,-1,anonymous_c1_645,anonymous_c2_7206,5,18,199
20,handle_248735,id_1000036,computer_os_type_133,computer_browser_version_875,country_146,0,anonymous_c1_1318,anonymous_c2_22839,28,110,204
21,handle_2061632,id_1000037,computer_os_type_243,computer_browser_version_1395,country_146,0,-1,-1,5,1,194
22,handle_1851795,id_1000038,computer_os_type_203,computer_browser_version_875,country_146,0,anonymous_c1_78,anonymous_c2_24726,25,1,196
23,handle_1068291,id_1000039,computer_os_type_203,computer_browser_version_875,-1,1,anonymous_c1_844,-1,14,1,200
24,handle_1913675,id_1000042,computer_os_type_203,computer_browser_version_1158,-1,0,-1,-1,26,172,204
25,handle_47701,id_1000048,computer_os_type_203,computer_browser_version_875,-1,-1,-1,-1,12,1,197
26,handle_2059273,id_1000050,computer_os_type_203,computer_browser_version_875,country_169,-1,anonymous_c1_211,-1,16,1,196
27,handle_1724748,id_1000051,computer_os_type_133,computer_browser_version_36,country_146,0,anonymous_c1_1286,anonymous_c2_22618,10,153,183
28,handle_523401,id_1000055,computer_os_type_203,computer_browser_version_683,country_146,-1,anonymous_c1_276,anonymous_c2_4752,2,182,183
29,handle_87379,id_1000056,computer_os_type_151,computer_browser_version_1620,country_146,1,anonymous_c1_41,anonymous_c2_8400,9,1,201
...,...,...,...,...,...,...,...,...,...,...,...
2175490,-1,id_999944,computer_os_type_133,computer_browser_version_875,country_146,0,anonymous_c1_1039,-1,7,172,196
2175491,handle_1061028,id_999946,computer_os_type_133,computer_browser_version_683,country_146,1,anonymous_c1_470,anonymous_c2_21871,10,106,195
2175492,handle_88234,id_999947,computer_os_type_201,computer_browser_version_875,country_4,-1,anonymous_c1_60,anonymous_c2_17415,9,1,204
2175493,handle_215883,id_999948,computer_os_type_203,computer_browser_version_36,country_146,0,anonymous_c1_455,anonymous_c2_25087,9,145,196
2175494,handle_1849065,id_99995,computer_os_type_164,computer_browser_version_875,country_146,0,anonymous_c1_505,anonymous_c2_6354,35,1,204
2175495,handle_1450942,id_999950,computer_os_type_248,computer_browser_version_1158,country_146,0,anonymous_c1_255,anonymous_c2_26299,5,194,201
2175496,handle_767887,id_999951,computer_os_type_203,computer_browser_version_875,country_146,1,anonymous_c1_250,-1,44,99,204
2175497,handle_1860209,id_999952,computer_os_type_200,computer_browser_version_645,country_146,1,-1,-1,46,1,204
2175498,handle_567478,id_999953,computer_os_type_200,computer_browser_version_482,country_146,0,anonymous_c1_1086,anonymous_c2_1334,6,193,202
2175499,-1,id_999954,computer_os_type_203,computer_browser_version_36,country_146,0,anonymous_c1_1086,anonymous_c2_31678,5,105,156
2175500,handle_1598204,id_99996,computer_os_type_203,computer_browser_version_377,country_146,0,anonymous_c1_804,anonymous_c2_29202,12,115,178
2175501,-1,id_999961,computer_os_type_203,computer_browser_version_875,country_168,0,anonymous_c1_1410,anonymous_c2_15009,9,141,200
2175502,handle_1153459,id_999962,computer_os_type_203,computer_browser_version_377,country_146,1,anonymous_c1_94,anonymous_c2_17262,4,1,203
2175503,handle_2012104,id_999965,computer_os_type_39,computer_browser_version_1620,country_146,0,anonymous_c1_255,anonymous_c2_29197,13,11,204
2175504,-1,id_999966,computer_os_type_70,computer_browser_version_1238,country_146,-1,-1,-1,1,152,152
2175505,-1,id_999967,computer_os_type_203,computer_browser_version_897,country_146,0,anonymous_c1_276,anonymous_c2_17894,1,84,149
2175506,handle_1655772,id_999969,computer_os_type_39,computer_browser_version_894,country_146,-1,anonymous_c1_648,anonymous_c2_2217,45,1,204
2175507,handle_995610,id_999970,computer_os_type_133,computer_browser_version_875,country_146,0,anonymous_c1_60,anonymous_c2_26167,30,158,204
2175508,handle_1159003,id_999973,computer_os_type_243,computer_browser_version_821,country_146,1,anonymous_c1_60,anonymous_c2_5262,27,141,204
2175509,-1,id_999974,computer_os_type_228,computer_browser_version_701,country_146,1,anonymous_c1_495,anonymous_c2_19773,16,1,198
2175510,handle_359440,id_999977,computer_os_type_203,computer_browser_version_1238,-1,1,anonymous_c1_1344,anonymous_c2_21142,4,124,145
2175511,handle_915360,id_999978,computer_os_type_203,computer_browser_version_36,country_146,0,anonymous_c1_1179,anonymous_c2_7482,8,185,195
2175512,-1,id_999981,computer_os_type_185,computer_browser_version_1212,country_146,0,-1,-1,52,1,204
2175513,-1,id_999982,computer_os_type_133,computer_browser_version_36,country_146,0,anonymous_c1_407,anonymous_c2_12037,2,148,198
2175514,-1,id_999987,computer_os_type_133,computer_browser_version_875,country_146,0,anonymous_c1_853,anonymous_c2_5008,19,169,199
2175515,-1,id_99999,computer_os_type_133,computer_browser_version_493,country_146,-1,-1,-1,1,148,148
2175516,-1,id_999991,computer_os_type_203,computer_browser_version_1158,country_146,0,anonymous_c1_1157,anonymous_c2_9085,30,169,204
2175517,handle_596633,id_999992,-1,computer_browser_version_1280,country_146,0,-1,-1,34,60,203
2175518,-1,id_999995,computer_os_type_203,computer_browser_version_1238,country_146,-1,anonymous_c1_1139,-1,1,172,172
2175519,handle_38844,id_999999,computer_os_type_109,computer_browser_version_875,country_146,1,anonymous_c1_906,anonymous_c2_4906,9,1,204

### Mobiles and Desktops Merging

In [103]:
feature_key = 'drawbridge_handle'
mobiles_sample = mobiles.loc[:200000]
mobiles_sample = mobiles_sample[mobiles_sample[feature_key] != '-1']
desktops_sample = desktops.loc[:200000]
desktops_sample = desktops_sample[desktops_sample[feature_key] != '-1']

In [112]:
pd.merge(cookies_sample, devices_sample,
         on= feature_key,
         how='inner', sort=True)[['anonymous_c0_x', 'anonymous_c0_y', 'anonymous_c1_x', 'anonymous_c1_y', 'anonymous_c2_x', 'anonymous_c2_y', 'anonymous_5_x', 'anonymous_5_y', 'anonymous_6_x', 'anonymous_6_y', 'anonymous_7_x', 'anonymous_7_y']]

,anonymous_c0_x,anonymous_c0_y,anonymous_c1_x,anonymous_c1_y,anonymous_c2_x,anonymous_c2_y,anonymous_5_x,anonymous_5_y,anonymous_6_x,anonymous_6_y,anonymous_7_x,anonymous_7_y
0,0,1,anonymous_c1_1294,anonymous_c1_501,anonymous_c2_26623,anonymous_c2_13432,1,34,189,1,189,204
1,-1,1,anonymous_c1_255,anonymous_c1_501,anonymous_c2_13432,anonymous_c2_13432,2,34,189,1,190,204
2,0,0,anonymous_c1_614,anonymous_c1_195,anonymous_c2_25937,anonymous_c2_25937,20,23,1,92,203,202
3,-1,-1,anonymous_c1_961,-1,anonymous_c2_11286,-1,38,1,118,1,204,147
4,-1,0,anonymous_c1_1396,-1,-1,-1,2,3,18,18,194,189
5,1,-1,-1,anonymous_c1_32,-1,anonymous_c2_25639,21,44,1,81,204,204
6,0,0,anonymous_c1_191,anonymous_c1_812,-1,anonymous_c2_13698,17,25,124,4,168,202
7,0,0,-1,anonymous_c1_535,-1,-1,25,14,107,60,203,176
8,1,0,anonymous_c1_1311,anonymous_c1_917,anonymous_c2_20004,anonymous_c2_24278,7,18,11,1,204,202
9,1,0,anonymous_c1_315,anonymous_c1_315,anonymous_c2_30526,anonymous_c2_22138,28,31,1,1,204,190
10,-1,1,anonymous_c1_527,-1,anonymous_c2_10006,-1,1,46,165,1,165,204
11,1,0,anonymous_c1_1086,anonymous_c1_420,anonymous_c2_29595,anonymous_c2_14533,6,52,1,1,204,204
12,0,0,anonymous_c1_426,anonymous_c1_1196,anonymous_c2_24500,-1,24,7,4,1,204,202
13,0,1,anonymous_c1_469,anonymous_c1_1086,anonymous_c2_10833,anonymous_c2_12124,9,33,179,1,190,201
14,-1,-1,-1,-1,-1,-1,1,2,186,1,186,191
15,-1,-1,anonymous_c1_226,anonymous_c1_34,anonymous_c2_3447,anonymous_c2_20643,1,10,1,1,174,204
16,-1,1,anonymous_c1_209,anonymous_c1_96,anonymous_c2_8567,anonymous_c2_4678,5,26,141,1,146,199
17,-1,-1,anonymous_c1_1055,anonymous_c1_60,anonymous_c2_25027,anonymous_c2_23728,3,2,74,1,187,199
18,-1,0,anonymous_c1_162,anonymous_c1_1123,anonymous_c2_10313,anonymous_c2_14887,1,1,152,1,167,170
19,0,-1,anonymous_c1_1089,anonymous_c1_700,anonymous_c2_15799,anonymous_c2_30171,46,10,136,11,194,198
20,-1,0,anonymous_c1_542,-1,anonymous_c2_29277,-1,8,7,1,1,185,200
21,1,0,anonymous_c1_1179,anonymous_c1_526,anonymous_c2_5390,anonymous_c2_13792,17,3,133,1,204,204
22,0,1,anonymous_c1_1233,-1,anonymous_c2_20479,-1,2,30,90,166,166,203
23,1,1,-1,anonymous_c1_1009,-1,anonymous_c2_19741,28,29,1,150,204,192
24,1,1,-1,anonymous_c1_510,-1,-1,28,3,1,1,204,149
25,-1,1,anonymous_c1_648,anonymous_c1_648,anonymous_c2_3611,anonymous_c2_3611,1,19,155,118,155,202
26,0,0,anonymous_c1_204,anonymous_c1_486,anonymous_c2_130,anonymous_c2_30073,3,4,1,83,194,181
27,0,-1,anonymous_c1_204,anonymous_c1_253,anonymous_c2_130,anonymous_c2_30073,3,52,1,1,194,204
28,0,1,anonymous_c1_1307,anonymous_c1_1307,anonymous_c2_4611,anonymous_c2_4611,1,11,188,1,188,198
29,0,0,-1,anonymous_c1_757,-1,anonymous_c2_7024,40,2,1,1,201,177
...,...,...,...,...,...,...,...,...,...,...,...,...
16645,0,0,anonymous_c1_331,anonymous_c1_331,anonymous_c2_13238,anonymous_c2_13238,23,18,146,81,176,204
16646,0,0,anonymous_c1_427,anonymous_c1_255,anonymous_c2_11013,anonymous_c2_11013,26,5,1,97,204,187
16647,0,1,anonymous_c1_365,-1,anonymous_c2_11600,-1,40,2,144,1,202,162
16648,0,1,anonymous_c1_255,anonymous_c1_652,anonymous_c2_17752,-1,3,20,140,1,144,203
16649,0,-1,anonymous_c1_686,anonymous_c1_455,anonymous_c2_1132,anonymous_c2_18986,20,5,67,1,197,201
16650,0,-1,anonymous_c1_881,anonymous_c1_1311,anonymous_c2_23244,anonymous_c2_5606,15,6,106,1,159,200
16651,-1,0,anonymous_c1_238,anonymous_c1_906,anonymous_c2_11111,anonymous_c2_23016,5,34,188,1,196,202
16652,0,1,anonymous_c1_1005,anonymous_c1_673,anonymous_c2_13967,anonymous_c2_27019,6,10,161,11,185,176
16653,0,-1,anonymous_c1_1086,anonymous_c1_1086,anonymous_c2_8622,-1,12,27,139,1,171,203
16654,-1,0,-1,anonymous_c1_77,-1,-1,1,11,189,4,189,200
16655,0,0,anonymous_c1_835,anonymous_c1_916,anonymous_c2_11717,anonymous_c2_26654,33,7,81,25,204,186
16656,1,1,anonymous_c1_724,anonymous_c1_896,anonymous_c2_23041,anonymous_c2_15883,44,26,155,1,204,203
16657,0,0,anonymous_c1_936,anonymous_c1_749,anonymous_c2_3321,anonymous_c2_31146,48,6,142,32,204,147
16658,0,0,anonymous_c1_315,anonymous_c1_749,anonymous_c2_3321,anonymous_c2_31146,12,6,114,32,201,147
16659,-1,-1,anonymous_c1_1111,-1,anonymous_c2_18552,-1,7,7,186,1,203,203
16660,0,1,anonymous_c1_255,-1,anonymous_c2_5881,-1,14,1,176,32,203,193
16661,0,1,anonymous_c1_1062,-1,anonymous_c2_22329,-1,17,16,91,1,201,200
16662,0,0,anonymous_c1_290,anonymous_c1_241,anonymous_c2_21935,anonymous_c2_18319,24,38,169,1,197,203
16663,-1,0,anonymous_c1_999,-1,anonymous_c2_27738,-1,39,43,96,1,204,203
16664,0,1,anonymous_c1_917,-1,anonymous_c2_829,-1,23,16,113,11,200,204
16665,1,-1,anonymous_c1_255,anonymous_c1_255,anonymous_c2_1238,anonymous_c2_1238,15,47,109,32,199,204
16666,1,1,anonymous_c1_1086,-1,anonymous_c2_9636,-1,8,26,53,39,194,204
16667,0,0,anonymous_c1_226,anonymous_c1_331,anonymous_c2_1997,anonymous_c2_26703,3,3,136,4,182,162
16668,0,-1,anonymous_c1_1307,anonymous_c1_93,anonymous_c2_1998,anonymous_c2_1998,20,9,83,128,167,179
16669,0,-1,-1,anonymous_c1_201,-1,anonymous_c2_27019,35,14,1,102,190,204
16670,-1,1,anonymous_c1_598,-1,anonymous_c2_18994,-1,1,21,148,1,148,204
16671,-1,1,anonymous_c1_1311,anonymous_c1_1409,anonymous_c2_23380,anonymous_c2_19390,4,18,182,1,191,183
16672,1,1,anonymous_c1_906,anonymous_c1_1013,anonymous_c2_8092,anonymous_c2_19260,20,5,116,1,203,199
16673,0,-1,anonymous_c1_331,anonymous_c1_331,anonymous_c2_27360,anonymous_c2_27360,52,11,32,129,204,198
16674,1,-1,anonymous_c1_341,-1,anonymous_c2_22375,-1,18,8,1,1,204,192

**Tips**

Consider a rule, with same person, we have `anonymous_c1_x` is equal with `anonymous_c1_y` or `anonymous_c2_x` is equal with `anonymous_c2_y`

## Test Set

In [305]:
mobiles_test = pd.read_csv('../input/dev_test_basic.csv')
mobiles_test

,drawbridge_handle,device_id,device_type,device_os,country,anonymous_c0,anonymous_c1,anonymous_c2,anonymous_5,anonymous_6,anonymous_7
0,-1,id_1,devtype_2,devos_72,country_146,1,-1,-1,52,1,204
1,-1,id_100002,devtype_4,devos_7,country_146,1,anonymous_c1_322,anonymous_c2_3059,7,1,149
2,-1,id_1000035,devtype_4,devos_68,country_146,-1,anonymous_c1_814,anonymous_c2_1918,17,106,201
3,-1,id_1000099,devtype_2,devos_159,country_146,0,anonymous_c1_736,-1,19,1,203
4,-1,id_1000294,devtype_4,devos_119,country_146,-1,anonymous_c1_261,anonymous_c2_17508,19,147,204
5,-1,id_1000305,devtype_4,devos_68,country_146,-1,anonymous_c1_144,anonymous_c2_29201,8,1,203
6,-1,id_1000310,devtype_2,devos_36,country_146,-1,anonymous_c1_510,anonymous_c2_15003,18,11,204
7,-1,id_1000414,devtype_2,devos_157,country_146,1,anonymous_c1_255,anonymous_c2_26303,16,1,202
8,-1,id_1000497,devtype_4,devos_114,country_146,-1,anonymous_c1_255,anonymous_c2_1927,16,18,204
9,-1,id_1000594,devtype_4,devos_68,country_146,-1,anonymous_c1_688,anonymous_c2_30854,4,1,188
10,-1,id_1000689,devtype_2,devos_72,country_146,0,anonymous_c1_1296,anonymous_c2_6217,26,25,204
11,-1,id_1000709,devtype_2,devos_36,country_201,-1,anonymous_c1_13,-1,9,113,191
12,-1,id_1000741,devtype_4,devos_119,country_146,-1,anonymous_c1_365,anonymous_c2_29085,3,11,188
13,-1,id_100079,devtype_4,devos_68,country_146,-1,-1,-1,3,1,198
14,-1,id_1000824,devtype_2,devos_34,country_146,0,anonymous_c1_176,anonymous_c2_7200,52,32,204
15,-1,id_1000868,devtype_4,devos_68,country_146,0,anonymous_c1_648,anonymous_c2_30026,41,46,204
16,-1,id_1000918,devtype_4,devos_119,country_146,1,anonymous_c1_1234,anonymous_c2_4674,22,1,204
17,-1,id_100095,devtype_2,devos_36,country_146,1,anonymous_c1_1068,anonymous_c2_30178,5,1,173
18,-1,id_1000964,devtype_2,devos_36,-1,0,-1,-1,3,11,185
19,-1,id_1001391,devtype_4,devos_119,country_146,1,-1,-1,3,1,194
20,-1,id_1001532,devtype_2,devos_57,country_146,0,anonymous_c1_1365,anonymous_c2_468,48,4,204
21,-1,id_100160,devtype_4,devos_119,country_146,-1,anonymous_c1_156,-1,8,1,186
22,-1,id_1001657,devtype_4,devos_68,country_146,-1,-1,-1,23,1,191
23,-1,id_1001701,devtype_2,devos_36,country_146,1,anonymous_c1_331,anonymous_c2_14675,4,4,204
24,-1,id_1001954,devtype_4,devos_68,country_146,0,anonymous_c1_60,anonymous_c2_15026,9,1,185
25,-1,id_1002053,devtype_2,devos_157,country_146,1,anonymous_c1_136,anonymous_c2_19656,52,81,204
26,-1,id_1002212,devtype_4,devos_7,country_146,1,anonymous_c1_136,-1,4,60,204
27,-1,id_1002223,devtype_4,devos_68,country_146,-1,anonymous_c1_417,anonymous_c2_4485,15,1,193
28,-1,id_1002230,devtype_4,devos_114,country_146,0,anonymous_c1_718,anonymous_c2_2982,21,39,204
29,-1,id_1002264,devtype_2,devos_157,country_146,0,anonymous_c1_455,anonymous_c2_4540,52,18,204
...,...,...,...,...,...,...,...,...,...,...,...
61126,-1,id_997605,devtype_4,devos_68,country_146,1,-1,-1,10,1,202
61127,-1,id_997854,devtype_4,devos_119,country_146,-1,-1,-1,21,100,191
61128,-1,id_997957,devtype_2,devos_36,country_146,0,-1,-1,2,1,194
61129,-1,id_997990,devtype_2,devos_138,country_146,0,anonymous_c1_884,-1,49,1,204
61130,-1,id_998035,devtype_4,devos_97,country_146,0,anonymous_c1_1015,anonymous_c2_31142,52,1,204
61131,-1,id_998069,devtype_4,devos_44,country_169,-1,anonymous_c1_559,anonymous_c2_23001,41,1,198
61132,-1,id_998130,devtype_2,devos_12,country_146,1,anonymous_c1_786,anonymous_c2_15976,50,60,203
61133,-1,id_998218,devtype_4,devos_133,country_146,0,anonymous_c1_1123,anonymous_c2_12270,14,1,204
61134,-1,id_998315,devtype_6,devos_157,country_146,0,anonymous_c1_1197,anonymous_c2_10383,11,1,202
61135,-1,id_998345,devtype_4,devos_68,country_146,1,-1,-1,3,1,195
61136,-1,id_998508,devtype_2,devos_157,country_169,1,anonymous_c1_543,anonymous_c2_1477,50,1,204
61137,-1,id_998566,devtype_2,devos_159,country_146,0,anonymous_c1_859,anonymous_c2_13418,13,94,202
61138,-1,id_998593,devtype_4,devos_68,country_146,1,anonymous_c1_1256,anonymous_c2_18846,11,106,193
61139,-1,id_998606,devtype_2,devos_157,country_146,0,-1,-1,30,25,203
61140,-1,id_998731,devtype_2,devos_36,country_146,0,anonymous_c1_204,anonymous_c2_30609,21,25,204
61141,-1,id_998794,devtype_4,devos_119,country_146,0,anonymous_c1_1187,anonymous_c2_3290,1,60,204
61142,-1,id_998942,devtype_2,devos_157,country_146,1,anonymous_c1_13,anonymous_c2_28686,27,81,204
61143,-1,id_998944,devtype_2,devos_157,country_201,-1,anonymous_c1_885,anonymous_c2_29080,52,1,204
61144,-1,id_999134,devtype_4,devos_68,country_146,-1,anonymous_c1_1086,anonymous_c2_13905,22,4,184
61145,-1,id_999179,devtype_4,devos_68,country_146,0,anonymous_c1_1164,anonymous_c2_24607,12,1,192
61146,-1,id_99918,devtype_4,devos_97,country_201,-1,anonymous_c1_1343,-1,1,1,177
61147,-1,id_999274,devtype_2,devos_159,country_146,-1,anonymous_c1_1307,-1,9,1,179
61148,-1,id_999338,devtype_4,devos_112,country_146,-1,anonymous_c1_1253,anonymous_c2_16263,4,1,204
61149,-1,id_999342,devtype_4,devos_133,country_146,-1,anonymous_c1_204,anonymous_c2_12471,10,1,201
61150,-1,id_999388,devtype_4,devos_119,country_146,0,anonymous_c1_1053,anonymous_c2_20037,20,1,196
61151,-1,id_999467,devtype_2,devos_138,country_146,1,anonymous_c1_492,anonymous_c2_24538,6,1,193
61152,-1,id_999511,devtype_2,devos_157,country_146,-1,-1,-1,39,1,204
61153,-1,id_999623,devtype_2,devos_159,country_146,0,-1,-1,16,67,189
61154,-1,id_999744,devtype_2,devos_138,country_146,0,anonymous_c1_255,-1,29,1,180
61155,-1,id_999865,devtype_5,devos_143,country_146,0,anonymous_c1_614,anonymous_c2_12852,8,1,194

In [311]:
mobiles_test_sample = mobiles_test
mobiles_test_sample = mobiles_test_sample[['device_id', 'anonymous_c2']].set_index(['anonymous_c2', 'device_id'])
desktops_sample = desktops[['cookie_id', 'anonymous_c2']].set_index(['anonymous_c2'])
merge_data = mobiles_test_sample.join(desktops_sample)

In [317]:
merge_data

In [315]:
bridges = merge_data.reset_index()[['device_id', 'cookie_id']]
bridges

,device_id,cookie_id
0,id_1,id_999995
1,id_100002,id_985898
2,id_1000035,id_971979
3,id_1000099,id_999995
4,id_1000294,id_919752
5,id_1000305,id_974295
6,id_1000310,id_997913
7,id_1000414,id_991442
8,id_1000497,id_999327
9,id_1000594,id_779029
10,id_1000689,id_956205
11,id_1000709,id_999995
12,id_1000741,id_99608
13,id_100079,id_999995
14,id_1000824,id_938154
15,id_1000868,id_99896
16,id_1000918,id_987712
17,id_100095,id_915987
18,id_1000964,id_999995
19,id_1001391,id_999995
20,id_1001532,id_87977
21,id_100160,id_999995
22,id_1001657,id_999995
23,id_1001701,id_998431
24,id_1001954,id_957845
25,id_1002053,id_905703
26,id_1002212,id_999995
27,id_1002223,id_968142
28,id_1002230,id_99118
29,id_1002264,id_882816
...,...,...
61126,id_997605,id_999995
61127,id_997854,id_999995
61128,id_997957,id_999995
61129,id_997990,id_999995
61130,id_998035,id_949757
61131,id_998069,id_999091
61132,id_998130,id_998342
61133,id_998218,id_926204
61134,id_998315,id_4680336
61135,id_998345,id_999995
61136,id_998508,id_686681
61137,id_998566,id_735702
61138,id_998593,id_943837
61139,id_998606,id_999995
61140,id_998731,id_995740
61141,id_998794,id_776196
61142,id_998942,id_995615
61143,id_998944,id_990885
61144,id_999134,id_989745
61145,id_999179,id_899984
61146,id_99918,id_999995
61147,id_999274,id_999995
61148,id_999338,id_947209
61149,id_999342,id_951353
61150,id_999388,id_783727
61151,id_999467,id_82538
61152,id_999511,id_999995
61153,id_999623,id_999995
61154,id_999744,id_999995
61155,id_999865,id_998570

In [316]:
create_submission(bridges)

In [ ]:
def